# -*- coding: utf-8 -*-
"""NBC Draft Pred

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FduXTtlJ4u11cx1M0S3rXTHcor8yOfBd
"""

import pandas as pd
import numpy as np
from sklearn_pandas import CategoricalImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Imputer
from sklearn.compose import ColumnTransformer

X = pd.read_csv("./data_loader/data/ncaa/player_stats.csv")

num_attribs = ['pts', 'fga', 'fga3', 'fgm', 'fgm3', 'fta', 'ftm', 'ast', 'blk', 'stl', 'dreb', 'oreb', 'reb', 'pf', 'tf', 'tov', 'mins_played', 'grade_level', 'division', 'height_in']
cat_attribs = ["school", "conference", "position"]

num_pipeline = Pipeline([
        ('imputer', Imputer(strategy="median")),
        ('std_scaler', StandardScaler())
    ])

cat_pipeline = Pipeline([
        ('imputer', CategoricalImputer()),
        ("cat", OneHotEncoder(handle_unknown='ignore'))
])

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        # ('imputer', CategoricalImputer(), cat_attribs),
        ("cat", OneHotEncoder(), cat_attribs)
])

working = full_pipeline.fit_transform(X)